live_config_reload: true

font:
  normal:
    family: Fira Code
    style: Regular
  size: 18.0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

# Colors (Monokai Pro)
colors:
  # Default colors
  primary:
    background: "#2D2A2E"
    foreground: "#FCFCFA"

  # Normal colors
  normal:
    black: "#403E41"
    red: "#FF6188"
    green: "#A9DC76"
    yellow: "#FFD866"
    blue: "#FC9867"
    magenta: "#AB9DF2"
    cyan: "#78DCE8"
    white: "#FCFCFA"

  # Bright colors
  bright:
    black: "#727072"
    red: "#FF6188"
    green: "#A9DC76"
    yellow: "#FFD866"
    blue: "#FC9867"
    magenta: "#AB9DF2"
    cyan: "#78DCE8"
    white: "#FCFCFA"

window:
  padding:
    x: 10
    y: 0
  dynamic_padding: true
  decorations: transparent

# shell:
#   program: /bin/zsh
#   args:
#     - -l
#     - -c
#     - tmux new-session -A -s main -c ~/git/newrelic

key_bindings:
  - { key: A, mods: Control, chars: "\x1bOH" }
  - { key: E, mods: Control, chars: "\x1bOF" }
  - { key: B, mods: Alt, chars: "\x1b\x62" }
  - { key: F, mods: Alt, chars: "\x1b\x66" }
