live_config_reload: true

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 18.0

draw_bold_text_with_bright_colors: true

# Colors (Monokai Pro)
colors:
  # Default colors
  primary:
    background: "#2d2a2e"
    foreground: "#fcfcfa"

  # Normal colors
  normal:
    black: "#403e41"
    red: "#ff6188"
    green: "#a9dc76"
    yellow: "#ffd866"
    blue: "#fc9867"
    magenta: "#ab9df2"
    cyan: "#78dce8"
    white: "#fcfcfa"

  # Bright colors
  bright:
    black: "#727072"
    red: "#ff6188"
    green: "#a9dc76"
    yellow: "#ffd866"
    blue: "#fc9867"
    magenta: "#ab9df2"
    cyan: "#78dce8"
    white: "#fcfcfa"

window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: buttonless
  option_as_alt: "Both"

shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main

# debug:
#   persistent_logging: false

key_bindings:
  - { key: A, mods: Control, chars: "\x1bOH" }
  - { key: E, mods: Control, chars: "\x1bOF" }
  - { key: B, mods: Alt, chars: "\x1b\x62" }
  - { key: F, mods: Alt, chars: "\x1b\x66" }
