live_config_reload: true

font:
  normal:
    family: Fira Code
    style: Regular 
  size: 18.0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

window:
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  decorations: transparent

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux aal"

key_bindings:
  - { key: A, mods: Control, chars: "\x1bOH"}
  - { key: E, mods: Control, chars: "\x1bOF"}
  - { key: W, mods: Alt, chars: "\x1b\x77"}
