format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmake\
$golang\
$nodejs\
$python\
$ruby\
$rust\
$terraform\
$kubernetes\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character"""
command_timeout = 1000

[git_branch]
format = "| [$symbol$branch]($style) "

[kubernetes]
disabled = false
format = "| [$symbol$context( \\($namespace\\))]($style) "
